#!/bin/bash
# Auto-Backup Script for Severin Cleaners Website
# Run this every 30 minutes while working: watch -n 1800 ./auto-backup.sh

echo "🔄 Auto-Backup Starting..."

# Check if there are changes
if [[ -n $(git status -s) ]]; then
    echo "📝 Changes detected, creating backup commit..."

    # Add all changes
    git add -A

    # Create backup commit with timestamp
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    git commit -m "AUTO-BACKUP: $TIMESTAMP

📦 Automatic backup commit
🤖 Generated by auto-backup.sh" || echo "⚠️  Nothing to commit or commit failed"

    # Push to GitHub
    echo "☁️  Pushing to GitHub..."
    git push origin master 2>&1 | grep -v "Everything up-to-date" || {
        echo "⚠️  Push failed - check your connection"
        exit 1
    }

    echo "✅ Backup complete and pushed to GitHub!"
else
    echo "✨ No changes to backup"
fi

echo "📊 Last 3 commits:"
git log --oneline -3

echo ""
echo "💾 Your work is safe on GitHub master branch"
